name: Node CI with NPM

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14, 16, 18]

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --network-timeout 3600000

    - name: Test CI
      uses: GabrielBB/xvfb-action@v1
      with:
        run: yarn test:ci

    - name: Coveralls coverage report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/scholars-angular/lcov.info
